version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_ENCRYPTION_KEY=long_random_secret_key_here
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - NODE_ENV=production
      - N8N_HOST=0.0.0.0
      - WEBHOOK_URL=https://theodorescsa.id.vn
      - N8N_SECURE_COOKIE=false
      - N8N_USER_MANAGEMENT_DISABLED=false

    volumes:
      - ./n8n-data:/home/node/.n8n

    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge

volumes:
  n8n_data: